/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerResponse } from './customer-response';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemResponse } from './order-item-response';

/**
 * 
 * @export
 * @interface OrderResponse
 */
export interface OrderResponse {
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'id'?: number;
    /**
     * 
     * @type {CustomerResponse}
     * @memberof OrderResponse
     */
    'customer'?: CustomerResponse;
    /**
     * 
     * @type {string}
     * @memberof OrderResponse
     */
    'orderDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {Array<OrderItemResponse>}
     * @memberof OrderResponse
     */
    'items'?: Array<OrderItemResponse>;
}

