/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerResponse } from './customer-response';

/**
 * 
 * @export
 * @interface PageResponseCustomerResponse
 */
export interface PageResponseCustomerResponse {
    /**
     * 
     * @type {Array<CustomerResponse>}
     * @memberof PageResponseCustomerResponse
     */
    'items'?: Array<CustomerResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCustomerResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCustomerResponse
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCustomerResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCustomerResponse
     */
    'totalPages'?: number;
}

