/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductCreateRequest
 */
export interface ProductCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductCreateRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateRequest
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateRequest
     */
    'quantityInStock': number;
}

