/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductResponse } from './product-response';
// May contain unused imports in some cases
// @ts-ignore
import type { SupplierResponse } from './supplier-response';

/**
 * 
 * @export
 * @interface StockEntryResponse
 */
export interface StockEntryResponse {
    /**
     * 
     * @type {number}
     * @memberof StockEntryResponse
     */
    'id'?: number;
    /**
     * 
     * @type {ProductResponse}
     * @memberof StockEntryResponse
     */
    'product'?: ProductResponse;
    /**
     * 
     * @type {SupplierResponse}
     * @memberof StockEntryResponse
     */
    'supplier'?: SupplierResponse;
    /**
     * 
     * @type {number}
     * @memberof StockEntryResponse
     */
    'quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof StockEntryResponse
     */
    'entryDate'?: string;
}

