/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StockEntryCreateRequest
 */
export interface StockEntryCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof StockEntryCreateRequest
     */
    'productId': number;
    /**
     * 
     * @type {number}
     * @memberof StockEntryCreateRequest
     */
    'supplierId': number;
    /**
     * 
     * @type {number}
     * @memberof StockEntryCreateRequest
     */
    'quantity': number;
    /**
     * 
     * @type {string}
     * @memberof StockEntryCreateRequest
     */
    'entryDate'?: string;
}

