/* tslint:disable */
/* eslint-disable */
/**
 * Spring Boot + MySQL – Inventory API
 * API mẫu cho dự án Spring Boot + MySQL + Docker. Bao gồm Products, Customers, Orders, Suppliers, Stock Management... Hỗ trợ pagination, validation, và exception handling. 
 *
 * The version of the OpenAPI document: v1
 * Contact: viettrungcntt03@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'role'?: string;
}

