spring:
  application:
    name: springboot-mysql-docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      indent_output: true

# SpringDoc OpenAPI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    default-model-expand-depth: 1
    default-models-expand-depth: 1
  api-docs:
    enabled: true
    path: /v3/api-docs

# Logging mặc định
logging:
  level:
    root: INFO
